name: cicd

env:
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
  CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  lint:
    name: install, lint, build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun i --ignore-scripts
      - run: bun run lint
      - run: bun run build
